OUTROOT=/scratch/local1/u246035/cGENIE/EMBM/cgenie_output
CODEDIR=/scratch/local1/u246035/cGENIE/EMBM/cgenie.muffin
RUNTIME_ROOT=../../cgenie.muffin
RUNTIME_OUTDIR=.
EXPID=RA.1P1Z-preC.SPIN
FIXEDATMOSFILE=data_fixedatmos
GLIMMERFILE=data_glimmer.config
igcm_module=genie-igcm
BFGROOT=EMPTY
MODULE_NAMES='embm goldstein goldsteinseaice biogem atchem ecogem '