        !COMPILER-GENERATED INTERFACE MODULE: Fri Mar  6 15:36:13 2020
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE DIAG_ECOGEM_TIMESLICE__genmod
          INTERFACE 
            SUBROUTINE DIAG_ECOGEM_TIMESLICE(DUM_DTS,DUM_GENIE_CLOCK,   &
     &DUM_GENIE_TSERIES,DUM_GENIE_TSLICE,DUM_GENIE_INTSERIES,           &
     &DUM_GENIE_INTSLICE,DUM_ENDSERIES,DUM_ENDSLICE,DUM_EGBG_FXSW,      &
     &DUM_MLD,DUM_EGBG_SFCOCN,DUM_EGBG_SFCPART,DUM_EGBG_SFCDISS)
              REAL(KIND=8), INTENT(IN) :: DUM_DTS
              INTEGER(KIND=8), INTENT(IN) :: DUM_GENIE_CLOCK
              REAL(KIND=8), INTENT(IN) :: DUM_GENIE_TSERIES
              REAL(KIND=8), INTENT(IN) :: DUM_GENIE_TSLICE
              LOGICAL(KIND=4), INTENT(IN) :: DUM_GENIE_INTSERIES
              LOGICAL(KIND=4), INTENT(IN) :: DUM_GENIE_INTSLICE
              LOGICAL(KIND=4), INTENT(IN) :: DUM_ENDSERIES
              LOGICAL(KIND=4), INTENT(IN) :: DUM_ENDSLICE
              REAL(KIND=8), INTENT(IN) :: DUM_EGBG_FXSW(36,36)
              REAL(KIND=8), INTENT(IN) :: DUM_MLD(36,36)
              REAL(KIND=8), INTENT(IN) :: DUM_EGBG_SFCOCN(101,36,36,32)
              REAL(KIND=8), INTENT(OUT) :: DUM_EGBG_SFCPART(87,36,36,32)
              REAL(KIND=8), INTENT(OUT) :: DUM_EGBG_SFCDISS(101,36,36,32&
     &)
            END SUBROUTINE DIAG_ECOGEM_TIMESLICE
          END INTERFACE 
        END MODULE DIAG_ECOGEM_TIMESLICE__genmod
